### ISSUE TITLE
Some feature ideas

### ISSUE THREAD

**Issue by vlascik** [Turbo87/intellij-emberjs#2]
Great work, finally a usable Ember plugin :)
Couple of ideas for features:
* {{component/helper/variable}} name completion in .hbs templates
* completion for i18n {{t helper, for ember-intl / ember-i18next (json, different directories) and ember-i18n (.js) 
* more live templates, maybe just copy them from https://github.com/kristianmandrup/emberjs-plugin

**Comment by Turbo87** [comment]
Thanks, glad you like it. 

Hbs completion might be a bit complicated since I'm not in control of the Hbs plugin, but I'll see what I can do. 

I'm not sure that all those live templates still make sense but there sure could be more. 

I've basically developed all the stuff that I've found useful while working on crates.io. I guess the next two things on my list will be test support and using ember-cli generators directly from the ide.

**Comment by vlascik** [comment]
Hm, I think .hbs shouldn't be a problem, looks like you'd just have to add completion contributor
https://confluence.jetbrains.com/display/IntelliJIDEA/Completion+Contributor . 
Translation completion is also useful in .js files, but as there is no standard for i18n in Ember, it might require some configuration options (translation function name, directory and format (json/js)). Should be doable though, i saw other plugins do it (e.g. laravel plugin adds similar completions to php, spring boot probably does something similar for java, etc.) and would save people quite a big amount of typing and guessing of correct translation keys.
Almost all live templates in the other plugin are still valid, it's possible to just import them manually from xml file anyway, but some (.s, .g being my favourites) would be helpful to everyone.
Generators would be nice to have, but it doesn't really save that much time compared to console, if any, imo.

**Comment by Turbo87** [comment]
v1.3.0 will have a few more live templates for Handlebars.

Closing this for now. I will accept PRs for Handlebars completion and the other suggested features but I'm probably not going to work on it myself.
