### ISSUE TITLE
Does not work with old IDE versions

### ISSUE THREAD

**Issue by tschoartschi** [Turbo87/intellij-emberjs#6]
Hey!

I wanted to try this plugin with my Webstorm 9 installation but I can not install it. During the installation I get the following error: 
```Error --> Plugin Ember.js is incompatible with current installation```
I have Webstorm 9.0.3 on Mac OS X Yosemite. Do I have a chance to get it running or is it really incompatible with my installation?

Thanks as lot

**Comment by Turbo87** [comment]
hmm that is unexpected. I tried to install the current version in WebStorm via the zip file an that seemed to work. But due to #4 this plugin is unfortunately not useable on WebStorm anyway as of now. I'm searching for solutions though.

**Comment by Turbo87** [comment]
could you try in the meantime if installing via https://github.com/Turbo87/intellij-emberjs/releases/download/v1.3.0/Ember.js-1.3.0.zip works for you?

**Comment by Turbo87** [comment]
hmm, I just noticed that WebStorm 9 is actually quite an old version since v11 seems to be current. I have no idea down until what version this plugin works or will be compatible. I'm developing it based on IntelliJ 15.0.1 and the minimum IDE version of the plugin is set to that version accordingly.

Can you tell me your exact version? Something like `143.382`.

**Comment by tschoartschi** [comment]
Maybe I should upgrade my WebStorm but right now time is quite short. Version 1.3.0 also does not work with WebStorm 9. Build version is ```139.1112```, WebStorm version is 9.0.3

Thanks a lot for your effort

**Comment by Turbo87** [comment]
I'll see if there is an intellij version matching that description.

**Comment by Turbo87** [comment]
it looks like the furthest I could go down in theory would be `14.1.1` (aka. `141.178.9` / see https://www.jetbrains.com/intellij-repository/releases). This is the first IntelliJ Ultimate release published on the JetBrains Maven repo that also contains associated source for the Community edition. Anything below that won't work work the JavaScript plugin so that is out of the question. I haven't yet had a look whether the APIs are actually compatible in any way and I actually have some doubts there...

**Comment by denofevil** [comment]
@Turbo87, hi from the WebStorm team here.
I haven't looked a lot at the plugin source code yet, but JavaScript API changed a LOT between 139 and 141 due to major internal changes

**Comment by tschoartschi** [comment]
@Turbo87 thanks for the effort. It's okay for met to close the issue

@denofevil great that the WebStorm team follows EmberJS. Will there be official EmberJS support any soon, or is it not on your roadmap?

**Comment by Turbo87** [comment]
@denofevil thanks for the feedback. I've experimented a bit with it and most of the stuff actually seems to work all the way back to `14.1.2`.

I might be able to make it work down to that release, but I will most likely wait with it until after my vacation. I wouldn't want to release such a major change before going offline for a few weeks...

**Comment by Turbo87** [comment]
@tschoartschi could you check if the [old-ide-compat](https://github.com/Turbo87/intellij-emberjs/tree/old-ide-compat) branch works for you? it will probably still be incompatible, but it should at least work down to `141.713.2`.
